#!/usr/bin/env python
import sys
from util.postscript import Postscript

def run(files):
    """
        2013-09-22:
            Nicely print all the files via enscript. Just print the source
    """
    for fullpath in files:
        splits = fullpath.split("/")
        # 2013-09-22: precarious!
        netid = splits[-2]
        fname = splits[-1]
        output_stream = Postscript(netid, fname)
        output_stream.write_code(fullpath)
        output_stream.close()

if __name__ == "__main__":
    run(sys.argv[1:])
